### ISSUE TITLE
Null pointer, not sure if related to craftconomy or EnjinMinecraftPlugin

### ISSUE THREAD

**Issue by Stuperfied** [Aztorius/craftconomy3#13]
[18:29:18 WARN]: [EnjinMinecraftPlugin] Task #37 for EnjinMinecraftPlugin v2.7.7 generated an exception
java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.hasAccount(Economy_Craftconomy3.java:254) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:10) ~[?:?]
        at com.enjin.officialplugin.EnjinMinecraftPlugin$1.run(EnjinMinecraftPlugin.java:857) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-b32c8f8-46226d6]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-b32c8f8-46226d6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-b32c8f8-46226d6]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-b32c8f8-46226d6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-b32c8f8-46226d6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-b32c8f8-46226d6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
>

**Comment by Aztorius** [comment]
It may be EnjinMinecraftPlugin using a null parameter with hasAccount() or the internal Craftconomy3 (but I don't think so, as you're the one to bring me this bug, and it works with other plugins).

**Comment by Aztorius** [comment]
Found it. Craftconomy currently support only old Vault API methods without UUID.
In order to support the new UUID methods, Craftconomy should be updated in many areas and Vault must be updated with a new version of Craftconomy3 methods.
So currently all plugins wich used ONLY new methods without checking will throw an exception with Craftconomy3.

**Comment by Aztorius** [comment]
Actually, Craftconomy works as expected. So this is very weird.
Can you send a complete log file and explain what version of Vault, Enjin and Craftconomy are you using ?

**Comment by Aztorius** [comment]
This error is linked to /ccsetup.
You need to setup craftconomy and then all of this should work correctly.

**Comment by Aztorius** [comment]
I confirm : **You need to setup craftconomy and then all of this should work correctly.**

**Comment by Stuperfied** [comment]
No default settings? ok, i'll check it out.
