### ISSUE TITLE
Crash with Sponge at startup : Could not pass GameStartedServerEvent$Impl to Plugin

### ISSUE THREAD

**Issue by Aztorius** [Aztorius/craftconomy3#15]
Currently, the plugin crash at startup of Sponge.

Tested with : 
- Sponge 1.11.2-6.0.0-BETA-239
- Sponge 1.10.2-5.2.0-BETA-385
- Sponge 1.9.4-5.0.0-BETA-83

`[09:38:17 ERROR] [Sponge]: Could not pass GameStartedServerEvent$Impl to Plugin{id=greatmancodetoolsloader, name=greatmancodetoolsloader, version=1.0, source=mods/craftconomy3-3.4.0-SNAPSHOT.jar}
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.greatmancode.craftconomy3.tools.interfaces.SpongeLoader.onEnable(SpongeLoader.java:68) ~[SpongeLoader.class:?]
        at com.greatmancode.craftconomy3.tools.interfaces.SpongeLoader.preInitialisationEvent(SpongeLoader.java:52) ~[SpongeLoader.class:?]`

**Comment by Aztorius** [comment]
Fixed in bf10d0d47c2fe64e49336d0d2a7ea5d3d9d838ae.

Working only with Sponge 1.10+
